Latest release and test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,13 +54,23 @@ jobs:
           CYPRESS_API_TOKEN: ${{ secrets.CYPRESS_API_TOKEN }}
           CYPRESS_PROJECT_ID: ${{ env.CYPRESS_PROJECT_ID }}
         run: |
-          QUERY=$(jq -n --arg projectId "$CYPRESS_PROJECT_ID" '{"query": "query { project(id: \"\($projectId)\") { runs(first: 1, orderBy: {direction: DESC, field: CREATED_AT}) { edges { node { runUrl } } } } }"}')
+          set -x  # Habilita el modo de depuración
+          QUERY=$(jq -n --arg projectId "$CYPRESS_PROJECT_ID" '{"query": "query { project(id: \"\($projectId)\") { runs(first: 1, orderBy: {direction: DESC, field: CREATED_AT}) { edges { node { id runUrl status } } } } }"}')
+          echo "GraphQL Query: $QUERY"
           RESPONSE=$(curl -s -X POST \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $CYPRESS_API_TOKEN" \
             -d "$QUERY" \
             https://cloud.cypress.io/graphql)
-          echo "Response: $RESPONSE"
+          echo "API Response: $RESPONSE"
+          ERRORS=$(echo "$RESPONSE" | jq -r '.errors')
+          if [ "$ERRORS" != "null" ]; then
+            echo "Error al obtener los datos de la API de Cypress:"
+            echo "$ERRORS"
+            exit 1
+          fi
+          RUNS_DATA=$(echo "$RESPONSE" | jq '.data.project.runs')
+          echo "Runs data: $RUNS_DATA"
           RUN_URL=$(echo "$RESPONSE" | jq -r '.data.project.runs.edges[0].node.runUrl')
           echo "Último RUN_URL: $RUN_URL"
           echo "CYPRESS_DASHBOARD_URL=$RUN_URL" >> $GITHUB_ENV
